This is the first map
```{r}
rm(world, population, airports)
```

```{r}
# install.packages("here")  # INSTALL IF NEEDED
library(here)
library(sf)
library(dplyr)
library(data.table)
library(ggplot2)

setwd(here())  # Sets working directory to the project root
population <- st_read(here("map_1/populated_places/ne_10m_populated_places.shp"))
airports <- st_read(here('map_1/airports/ne_10m_airports.shp'))
world <- st_read(here('map_1/countries/ne_10m_admin_0_countries.shp'))
```

We have found that Egypt's geometry data in the world dataframe is invalid, so we import a new shape file to substitute it.
```{r}
egypt <- st_read(here('map_1/countries/eg.shp'))
egypt_idx <- which(world$SOVEREIGNT == "Egypt")
world$geometry[egypt_idx] <- egypt$geometry[1]
rm(egypt)
```
```{r}
world <- world %>% 
          select(SOVEREIGNT, MAPCOLOR9, POP_EST, CONTINENT, REGION_UN, SUBREGION, LABEL_X, LABEL_Y, geometry) %>% 
          rename(geom_world = geometry)
population <- population %>% 
              select(SOV0NAME, LATITUDE, LONGITUDE, POP_MAX, geometry) %>% 
              rename(geom_popu = geometry)
airports <- airports %>% 
              select(featurecla, type, name, scalerank, abbrev, geometry) %>% 
              rename(geom_air = geometry)

merged_data <- st_join(world, population)

View(merged_data)
```
```{r}
View(merged_data)
```

```{r}
```
```{r}
View(world)
View(population)
View(airports)
```

```{r}
print(length(unique(airports$abbrev)))
print(length(unique(airports$iata_code)))
print(length(unique(airports$gps_code)))
```